# Generated by Django 2.1.7 on 2019-05-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoshi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='select',
            name='key',
            field=models.CharField(max_length=1),
        ),
    ]
