# Generated by Django 2.1.7 on 2019-05-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoshi', '0003_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='序号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='judge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='题号'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='key',
            field=models.BooleanField(verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='topic',
            field=models.TextField(verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='select',
            name='a',
            field=models.CharField(max_length=255, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='select',
            name='b',
            field=models.CharField(max_length=255, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='select',
            name='c',
            field=models.CharField(max_length=255, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='select',
            name='d',
            field=models.CharField(max_length=255, verbose_name='D选项'),
        ),
        migrations.AlterField(
            model_name='select',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='题号'),
        ),
        migrations.AlterField(
            model_name='select',
            name='key',
            field=models.CharField(max_length=1, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='select',
            name='topic',
            field=models.TextField(verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='a',
            field=models.CharField(max_length=255, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='b',
            field=models.CharField(max_length=255, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='c',
            field=models.CharField(max_length=255, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='d',
            field=models.CharField(max_length=255, verbose_name='D选项'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='题号'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='key',
            field=models.CharField(max_length=4, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='selects',
            name='topic',
            field=models.TextField(verbose_name='题目'),
        ),
    ]
