# Generated by Django 2.1.7 on 2019-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoshi', '0005_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='fraction',
            field=models.BigIntegerField(auto_created=True, default=0),
        ),
    ]
