# Generated by Django 2.1.7 on 2019-05-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoshi', '0006_auto_20190510_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='fraction',
            field=models.BigIntegerField(auto_created=True, default=1),
        ),
    ]
