# Generated by Django 2.1.7 on 2019-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaoshi', '0007_auto_20190510_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ftotal',
            field=models.BigIntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total',
            field=models.BigIntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ttotal',
            field=models.BigIntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fraction',
            field=models.BigIntegerField(auto_created=True, default=0),
        ),
    ]
